
title: Andrew Sai's Website
url: 'https://funandyx.github.io/andrewsai/'
baseurl: '/andrewsai' #change it according to your repository name



# Profile information
yourname: Andrew Sai  ## put your name
title: 'ANALYST &amp; LECTURER, RESEARCHER'  ## your title
location: Tallinn Estonia/San Francisco , CA


## Social Profiles
facebook: https://www.facebook.com/funandyx  ## your facebook account url
twitter: http://www.twitter.com/niiadjahsai  ## your twitter account url
linkedin: https://www.linkedin.com/in/andrewadjahsai/  ## your linkedin account url
instagram: https://www.instagram.com/funandyx/  ## you dribbble account url
github: http://www.github.com/funandyx  ## your foursquare account url
medium: https://medium.com/@andrewadjahsai ## my medium account url



# Update all the sections by editing the files inside _includes folder.
